// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;
using Microsoft.ML.Data;

// Create single instance of sample data from first line of dataset for model input
var image = MLImage.CreateFromFile(@"C:\not_labeld_images\Image_1550.png");
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    ImageSource = image,
};
// Make a single prediction on the sample data and print results.
var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine("\n\nPredicted Boxes:\n");
Console.WriteLine(predictionResult);

